name: Prettier Code Formatter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npx prettier --write .
      - name: Commit changes
        run: |
          git config --global user.name 'zzzuuu'
          git config --global user.email 'dreamoniz@gmail.com'
          git commit -am "Apply Prettier changes" || echo "No changes to commit"
          git push
